import type { Job, TrackedProfile } from "@/src/features/tracked-profiles/types";
import type {
  AnalysisRun,
  CommentSample,
  ContentScore,
  ContentMetricSnapshot,
  ExternalContent,
  Inspiration,
  Transcript,
} from "@/src/features/inspirations/types";
import type { DiscoverySearch } from "@/src/features/discovery/types";
import type { Pattern } from "@/src/features/patterns/types";
import type { ProviderUsageSummary } from "@/src/features/usage/types";

const now = Date.now();

export const demoProfiles: TrackedProfile[] = [
  {
    id: "80b12167-923c-4ec0-b3df-79f2ce64d76c",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    platform: "xiaohongshu",
    external_id: "sea-salt-notes",
    profile_url: "https://www.xiaohongshu.com/",
    display_name: "海盐商业笔记",
    avatar_url: null,
    handle: "@seasalt_lab",
    follower_count_latest: 284000,
    priority: 90,
    scan_policy_id: "19ca8d53-85db-49c7-b9d0-e5d7f73dc82f",
    last_synced_at: new Date(now - 18 * 60_000).toISOString(),
    next_scan_at: new Date(now + 5 * 60 * 60_000).toISOString(),
    sync_status: "idle",
    active: true,
    created_at: new Date(now - 42 * 86400_000).toISOString(),
    updated_at: new Date(now - 18 * 60_000).toISOString(),
  },
  {
    id: "232d40d1-f7d9-45da-9bbf-f4f7c96b9fbd",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    platform: "douyin",
    external_id: "content-observer",
    profile_url: "https://www.douyin.com/",
    display_name: "内容观察局",
    avatar_url: null,
    handle: "@content_scope",
    follower_count_latest: 963000,
    priority: 80,
    scan_policy_id: "19ca8d53-85db-49c7-b9d0-e5d7f73dc82f",
    last_synced_at: new Date(now - 2.5 * 60 * 60_000).toISOString(),
    next_scan_at: new Date(now + 3.5 * 60 * 60_000).toISOString(),
    sync_status: "running",
    active: true,
    created_at: new Date(now - 30 * 86400_000).toISOString(),
    updated_at: new Date(now - 2.5 * 60 * 60_000).toISOString(),
  },
  {
    id: "b66b3242-ac60-4a9b-83ab-728be74924a5",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    platform: "bilibili",
    external_id: "brand-casebook",
    profile_url: "https://www.bilibili.com/",
    display_name: "品牌案例簿",
    avatar_url: null,
    handle: "@brand_cases",
    follower_count_latest: 127000,
    priority: 65,
    scan_policy_id: "19ca8d53-85db-49c7-b9d0-e5d7f73dc82f",
    last_synced_at: new Date(now - 26 * 60 * 60_000).toISOString(),
    next_scan_at: null,
    sync_status: "paused",
    active: false,
    created_at: new Date(now - 18 * 86400_000).toISOString(),
    updated_at: new Date(now - 26 * 60 * 60_000).toISOString(),
  },
  {
    id: "00ac26c3-4312-4dfa-a1b9-23340282ffeb",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    platform: "youtube",
    external_id: "creator-insider",
    profile_url: "https://www.youtube.com/",
    display_name: "Creator Insider",
    avatar_url: null,
    handle: "@creatorinsider",
    follower_count_latest: null,
    priority: 55,
    scan_policy_id: "19ca8d53-85db-49c7-b9d0-e5d7f73dc82f",
    last_synced_at: new Date(now - 3 * 86400_000).toISOString(),
    next_scan_at: new Date(now + 45 * 60_000).toISOString(),
    sync_status: "failed",
    active: true,
    created_at: new Date(now - 10 * 86400_000).toISOString(),
    updated_at: new Date(now - 3 * 86400_000).toISOString(),
  },
];

export const demoJobs: Job[] = [
  {
    id: "356f03d7-7302-4e02-b37d-50046d71c095",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    job_type: "PROFILE_SCAN",
    status: "running",
    priority: 80,
    attempt: 1,
    max_attempts: 3,
    run_after: new Date(now - 2 * 60_000).toISOString(),
    last_error_code: null,
    last_error_message: null,
    result: null,
    created_at: new Date(now - 3 * 60_000).toISOString(),
    finished_at: null,
  },
  {
    id: "db058a16-d442-4917-9624-f48bd2abbdba",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    job_type: "PROFILE_SCAN",
    status: "failed",
    priority: 55,
    attempt: 3,
    max_attempts: 3,
    run_after: new Date(now - 3 * 86400_000).toISOString(),
    last_error_code: "PROVIDER_RATE_LIMITED",
    last_error_message: "数据源触发频率限制，请稍后重试。",
    result: null,
    created_at: new Date(now - 3 * 86400_000).toISOString(),
    finished_at: new Date(now - 3 * 86400_000 + 31_000).toISOString(),
  },
  {
    id: "5b412639-39d2-4875-8668-79c4a01dc273",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    job_type: "PROFILE_SCAN",
    status: "succeeded",
    priority: 90,
    attempt: 1,
    max_attempts: 3,
    run_after: new Date(now - 19 * 60_000).toISOString(),
    last_error_code: null,
    last_error_message: null,
    result: { imported_contents: 12 },
    created_at: new Date(now - 20 * 60_000).toISOString(),
    finished_at: new Date(now - 18 * 60_000).toISOString(),
  },
  {
    id: "7f962055-cd25-475a-9876-7ac8dfc0d68e",
    workspace_id: "7391ea11-9464-456d-bdc8-f7aa5ebf4d30",
    job_type: "PROFILE_SCAN",
    status: "pending",
    priority: 65,
    attempt: 0,
    max_attempts: 3,
    run_after: new Date(now + 2 * 60_000).toISOString(),
    last_error_code: null,
    last_error_message: null,
    result: null,
    created_at: new Date(now - 40_000).toISOString(),
    finished_at: null,
  },
];

export const demoContents: ExternalContent[] = [
  {
    id: "91d3e8c2-776d-430c-8e42-1df65efcc001",
    platform: "xiaohongshu",
    external_id: "xhs-growth-01",
    tracked_profile_id: demoProfiles[0].id,
    canonical_url: "https://www.xiaohongshu.com/explore/demo-growth",
    content_type: "note",
    title: "把品牌内容拆成三条可复用的增长线",
    body_text: "从真实用户问题出发，分别验证钩子、证据和行动指令。",
    published_at: new Date(now - 2 * 86400_000).toISOString(),
    duration_ms: null,
    author_snapshot: { display_name: "海盐商业笔记" },
    media_manifest: [],
    detail_status: "ready",
    first_seen_at: new Date(now - 36 * 60 * 60_000).toISOString(),
    last_seen_at: new Date(now - 18 * 60_000).toISOString(),
  },
  {
    id: "91d3e8c2-776d-430c-8e42-1df65efcc002",
    platform: "douyin",
    external_id: "dy-hook-02",
    tracked_profile_id: demoProfiles[1].id,
    canonical_url: "https://www.douyin.com/video/demo-hook",
    content_type: "video",
    title: "前三秒不是更吵，而是更具体",
    body_text: "用场景和损失替代空泛的反问，让受众立刻判断内容是否与自己有关。",
    published_at: new Date(now - 4 * 86400_000).toISOString(),
    duration_ms: 47_000,
    author_snapshot: { display_name: "内容观察局" },
    media_manifest: [],
    detail_status: "ready",
    first_seen_at: new Date(now - 3 * 86400_000).toISOString(),
    last_seen_at: new Date(now - 2.5 * 60 * 60_000).toISOString(),
  },
  {
    id: "91d3e8c2-776d-430c-8e42-1df65efcc003",
    platform: "bilibili",
    external_id: "bili-case-03",
    tracked_profile_id: demoProfiles[2].id,
    canonical_url: "https://www.bilibili.com/video/demo-case",
    content_type: "video",
    title: "一个餐饮品牌如何持续产出本地内容",
    body_text: "案例拆解：选题池、拍摄日和一稿多发的协作方式。",
    published_at: new Date(now - 7 * 86400_000).toISOString(),
    duration_ms: 385_000,
    author_snapshot: { display_name: "品牌案例簿" },
    media_manifest: [],
    detail_status: "summary",
    first_seen_at: new Date(now - 6 * 86400_000).toISOString(),
    last_seen_at: new Date(now - 26 * 60 * 60_000).toISOString(),
  },
];

export const demoInspirations: Inspiration[] = demoContents.map(
  (content, index) => ({
    id: [
      "a11d18b5-aeb6-4fc1-a146-1c1cd843a001",
      "a11d18b5-aeb6-4fc1-a146-1c1cd843a002",
      "a11d18b5-aeb6-4fc1-a146-1c1cd843a003",
    ][index],
    status: ["candidate", "analyzed", "inbox"][index],
    source: index === 2 ? "profile_scan" : "manual_url",
    notes: index === 0 ? "可迁移到餐饮商家增长内容。" : null,
    manual_score: index === 0 ? 88 : null,
    created_at: content.first_seen_at,
    updated_at: content.last_seen_at,
    content,
    latest_score:
      index === 0
        ? {
            grade: "t1",
            r_value: "5.74",
            m_value: "0.81",
            calculated_at: new Date(now - 17 * 60_000).toISOString(),
          }
        : null,
    latest_metrics:
      index === 0
        ? {
            captured_at: new Date(now - 17 * 60_000).toISOString(),
            views: null,
            likes: 6280,
            comments: 214,
            favorites: 1900,
            shares: null,
          }
        : null,
  }),
);

export const demoScores: ContentScore[] = [
  {
    id: "4ef0b930-64c5-44ce-86d9-fcab0d252f24",
    external_content_id: demoContents[0].id,
    scoring_policy_id: "19ca8d53-85db-49c7-b9d0-e5d7f73dc82f",
    calculated_at: new Date(now - 17 * 60_000).toISOString(),
    r_value: "2.74",
    m_value: "0.81",
    tier: "A",
    grade: "A",
    core_metric: "engagement_rate",
    baseline_value: "1.00",
    is_initial: false,
    evidence: { sample: "latest_snapshot" },
  },
];

export const demoMetrics: ContentMetricSnapshot[] = [
  {
    id: "29ce928e-5463-463f-b1ea-cd225e7b5001",
    external_content_id: demoContents[0].id,
    captured_at: new Date(now - 17 * 60_000).toISOString(),
    views: null,
    likes: 6280,
    comments: 214,
    favorites: 1900,
    shares: null,
    downloads: null,
    metrics: {},
  },
  {
    id: "29ce928e-5463-463f-b1ea-cd225e7b5002",
    external_content_id: demoContents[0].id,
    captured_at: new Date(now - 24 * 60 * 60_000).toISOString(),
    views: null,
    likes: 5910,
    comments: 198,
    favorites: 1740,
    shares: null,
    downloads: null,
    metrics: {},
  },
];

export const demoComments: CommentSample[] = [
  {
    id: "56698d0f-e451-4a2a-9c55-c8621c8cc001",
    external_comment_id: "comment-demo-1",
    parent_external_id: null,
    author_snapshot: { display_name: "小满" },
    body_text: "终于讲清楚了选题和内容格式不是一回事。",
    like_count: 36,
    published_at: new Date(now - 22 * 60 * 60_000).toISOString(),
    captured_at: new Date(now - 17 * 60_000).toISOString(),
  },
  {
    id: "56698d0f-e451-4a2a-9c55-c8621c8cc002",
    external_comment_id: "comment-demo-2",
    parent_external_id: null,
    author_snapshot: { display_name: "Leo" },
    body_text: "想看餐饮门店的完整例子。",
    like_count: 12,
    published_at: new Date(now - 18 * 60 * 60_000).toISOString(),
    captured_at: new Date(now - 17 * 60_000).toISOString(),
  },
];

export const demoAnalyses: AnalysisRun[] = [
  {
    id: "40437748-d779-4fc0-8b6e-e934c81d3401",
    external_content_id: demoContents[0].id,
    sync_job_id: null,
    ai_connection_id: null,
    analysis_level: "l1",
    model_provider: "demo",
    model: "content-analyst",
    prompt_version: "v1",
    input_hash: "demo-input",
    status: "succeeded",
    result: {
      hook: "用三条增长线承诺清晰的拆解结果",
      audience: "需要建立稳定内容流程的品牌运营者",
      structure: "痛点 → 三线框架 → 行动建议",
    },
    evidence_refs: [],
    input_tokens: 720,
    output_tokens: 280,
    cost_usd: "0.0000",
    latency_ms: 1280,
    error_code: null,
    created_at: new Date(now - 15 * 60_000).toISOString(),
    finished_at: new Date(now - 15 * 60_000 + 1280).toISOString(),
  },
];

export const demoTranscripts: Transcript[] = [
  {
    id: "0dcd2b71-e407-4217-940d-b0c14fd56501",
    external_content_id: demoContents[0].id,
    sync_job_id: null,
    provider: "demo",
    model: "speech-to-text",
    language: "zh",
    status: "succeeded",
    text: "增长不是每天追热点，而是让每条内容承担一个明确任务。",
    segments: null,
    confidence: "0.96",
    input_hash: "demo-audio",
    cost_usd: "0.0000",
    error_code: null,
    created_at: new Date(now - 16 * 60_000).toISOString(),
    finished_at: new Date(now - 16 * 60_000 + 980).toISOString(),
  },
];

export const demoDiscoverySearch: DiscoverySearch = {
  id: "cf461b21-6f43-49a7-8eb2-639aef9a3010",
  sync_job_id: "cf461b21-6f43-49a7-8eb2-639aef9a3020",
  platform: "xiaohongshu",
  query: "餐饮运营",
  max_pages: 1,
  hydrate_top: 3,
  parameters: {
    sort_type: "popularity_descending",
    note_type: "不限",
    time_filter: "一周内",
  },
  status: "succeeded",
  result_count: 3,
  error_code: null,
  created_at: new Date(now - 8 * 60_000).toISOString(),
  finished_at: new Date(now - 7 * 60_000).toISOString(),
  results: [
    {
      id: "3b1e9758-e03a-4208-b059-0f29805cc001",
      platform: "xiaohongshu",
      external_id: "discovery-demo-1",
      result_rank: 1,
      imported_external_content_id: null,
      summary: {
        title: "门店不降价，也能让顾客主动发笔记的三个细节",
        body_text: "把可分享的瞬间设计进服务流程，而不是临时要求顾客打卡。",
        canonical_url: "https://www.xiaohongshu.com/explore/discovery-demo-1",
        author_snapshot: { display_name: "本地生意研究社" },
        metrics: { likes: 6280, comments: 214, favorites: 1900 },
      },
    },
    {
      id: "3b1e9758-e03a-4208-b059-0f29805cc002",
      platform: "xiaohongshu",
      external_id: "discovery-demo-2",
      result_rank: 2,
      imported_external_content_id: demoContents[0].id,
      summary: {
        title: "餐饮老板每周只看这四个内容指标",
        body_text: "先确认内容是否带来有效到店意图，再讨论播放量。",
        canonical_url: "https://www.xiaohongshu.com/explore/discovery-demo-2",
        author_snapshot: { display_name: "餐饮增长手册" },
        metrics: { likes: 4120, comments: null, favorites: 980 },
      },
    },
    {
      id: "3b1e9758-e03a-4208-b059-0f29805cc003",
      platform: "xiaohongshu",
      external_id: "discovery-demo-3",
      result_rank: 3,
      imported_external_content_id: null,
      summary: {
        title: "探店内容为什么越来越难转化",
        body_text: "问题不只在达人报价，而在内容承诺与门店体验不一致。",
        canonical_url: "https://www.xiaohongshu.com/explore/discovery-demo-3",
        author_snapshot: { display_name: "线下观察员" },
        metrics: { likes: 2870, comments: 96, favorites: null },
      },
    },
  ],
};

export const demoPatterns: Pattern[] = [
  {
    id: "807dd26b-7cc0-4882-b421-6333f1938001",
    name: "具体损失开场",
    description:
      "前三秒直接点明受众正在损失的时间、费用或机会，再给出可验证的解决路径。",
    pattern_type: "hook",
    applicable_channels: ["xiaohongshu", "douyin"],
    source_content_ids: [demoContents[0].id, demoContents[1].id],
    evidence: {
      success_count: 6,
      failure_count: 1,
      limitations: "不适合纯品牌形象片或缺乏可靠数据的主题",
    },
    status: "validated",
    created_by: null,
    created_at: new Date(now - 20 * 86400_000).toISOString(),
    updated_at: new Date(now - 2 * 86400_000).toISOString(),
  },
  {
    id: "807dd26b-7cc0-4882-b421-6333f1938002",
    name: "三段证据链",
    description: "用真实场景、过程证据和结果证据依次降低受众怀疑。",
    pattern_type: "structure",
    applicable_channels: ["xiaohongshu"],
    source_content_ids: [demoContents[0].id],
    evidence: {
      success_count: 2,
      failure_count: 0,
      limitations: "需要至少一项可核验结果",
    },
    status: "draft",
    created_by: null,
    created_at: new Date(now - 5 * 86400_000).toISOString(),
    updated_at: new Date(now - 5 * 86400_000).toISOString(),
  },
  {
    id: "807dd26b-7cc0-4882-b421-6333f1938003",
    name: "泛人群反问句",
    description: "以宽泛反问开场，曾经用于快速制造情绪但转化证据不足。",
    pattern_type: "hook",
    applicable_channels: ["douyin"],
    source_content_ids: [],
    evidence: {
      success_count: 1,
      failure_count: 5,
      limitations: "人群不明确，容易获得无效播放",
    },
    status: "retired",
    created_by: null,
    created_at: new Date(now - 40 * 86400_000).toISOString(),
    updated_at: new Date(now - 10 * 86400_000).toISOString(),
  },
];

export const demoProviderUsage: ProviderUsageSummary = {
  request_count: 126,
  success_count: 119,
  billable_count: 84,
  estimated_cost_usd: "2.8400",
  items: [
    {
      usage_date: new Date(now).toISOString().slice(0, 10),
      provider: "tikhub",
      endpoint_key: "xhs.search_notes",
      request_count: 18,
      success_count: 17,
      billable_count: 12,
      estimated_cost_usd: "0.6200",
    },
    {
      usage_date: new Date(now - 86400_000).toISOString().slice(0, 10),
      provider: "tikhub",
      endpoint_key: "xhs.note_detail",
      request_count: 42,
      success_count: 40,
      billable_count: 32,
      estimated_cost_usd: "1.1800",
    },
    {
      usage_date: new Date(now - 2 * 86400_000).toISOString().slice(0, 10),
      provider: "tikhub",
      endpoint_key: "xhs.user_notes",
      request_count: 66,
      success_count: 62,
      billable_count: 40,
      estimated_cost_usd: "1.0400",
    },
  ],
};
